[package]
name = "NabobTokenObjects"
version = "1.0.0"

[addresses]
std = "0x1"
nabob_std = "0x1"
nabob_framework = "0x1"
nabob_token_objects = "0x4"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
NabobFramework = { local = "../nabob-framework"}
